// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV-8_6jex9wOeeVdgIKAKCxUTWX7W6FAM',
    appId: '1:760954712960:web:0165d8e5a9f33751bd0765',
    messagingSenderId: '760954712960',
    projectId: 'todoapp-c71de',
    authDomain: 'todoapp-c71de.firebaseapp.com',
    storageBucket: 'todoapp-c71de.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUg9c6MfHe_0fhYtXRoAptxYKqtEWdLaQ',
    appId: '1:760954712960:android:059ff3362a208a59bd0765',
    messagingSenderId: '760954712960',
    projectId: 'todoapp-c71de',
    storageBucket: 'todoapp-c71de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwL2lSiMAxCMg8wc1QiviDTuIlQwW_NvM',
    appId: '1:760954712960:ios:7002402590e5fa20bd0765',
    messagingSenderId: '760954712960',
    projectId: 'todoapp-c71de',
    storageBucket: 'todoapp-c71de.appspot.com',
    iosClientId: '760954712960-cugjbg9qsc2o3dhcivhuqodmgsl2bjt5.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
